apiVersion: apps/v1
kind: Deployment
metadata:
  name: olivetti-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: olivetti
  template:
    metadata:
      labels:
        app: olivetti
    spec:
      containers:
        - name: olivetti-container
          image: nalin08--docker/olivetti-app:latest
          ports:
            - containerPort: 5000
